# This file was generated by GoReleaser. DO NOT EDIT.
cask "lunchtui" do
  name "lunchtui"
  desc "A beautiful command-line interface for your Lunch Money account"
  homepage "https://github.com/Rshep3087/lunchtui"
  version "0.26.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lunchtui"

  on_macos do
    on_intel do
      url "https://github.com/Rshep3087/lunchtui/releases/download/v#{version}/lunchtui_Darwin_x86_64.tar.gz"
      sha256 "0e8c90e62cfd2e603efa0c5de15d73349c71223fca8af588f57057486d7ebadf"
    end
    on_arm do
      url "https://github.com/Rshep3087/lunchtui/releases/download/v#{version}/lunchtui_Darwin_arm64.tar.gz"
      sha256 "8d628a50a921d6dbd355a5437ab24180885b20d1170b8344063a6eff10529133"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Rshep3087/lunchtui/releases/download/v#{version}/lunchtui_Linux_x86_64.tar.gz"
      sha256 "2b242010c0fb571bc328d720f782b346395c9007965eb8a0aefd11e55e5794a7"
    end
    on_arm do
      url "https://github.com/Rshep3087/lunchtui/releases/download/v#{version}/lunchtui_Linux_arm64.tar.gz"
      sha256 "a064f2a171f91851e65574745d067702502b7d4034c5a1b43c508d70d95b9700"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lunchtui"]
  end

  # No zap stanza required
end
